### ISSUE TITLE
is libcurl exporting a function to parse the command line params?

### ISSUE THREAD

**Issue by dkuku** [open-status/ex_curl#8]
It would be useful to have a way to copy a request from the browser as curl and have a way to execute it from elixir.
Or even better to parse it first - have a way to edit the params and then send. Currently I use postman for this but livebook would be much better.

**Comment by danielrudn** [comment]
Hey, I am not aware of libcurl itself exposing the ability to parse the command line params. I thought your idea of using curl commands in livebooks was really interesting so I created a new library called [kino_curl](https://github.com/open-status/kino_curl) which adds a new `cURL Command` cell that allows using curl commands in Livebook by parsing and converting the command into Elixir code.
	  
Here is a gif demonstrating how it works:

<img src="https://user-images.githubusercontent.com/6834213/209873046-c327244d-acd5-4b21-ae07-bcc4429b607d.gif" height="600" />

You should be able to convert the smart cell into code in order to edit the parameters before sending as well.

**Comment by dkuku** [comment]
Thanks for looking into this. This is awesome. 
You can make a demo that copies the request from the browser and then pipe the result to https://github.com/spawnfest/the-arborists or a table then it will show it's full potential.
